service:
  name: halt-proj-gql

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    includeModules : true
  tableName: accounts

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: ap-southeast-1 # Overwrite the default region used. Default is us-east-1
  profile: halt-app-amplify-profile # The default profile to use with this service
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-${self:custom.tableName}  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - accountsTable
          - Arn

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true

resources:
  Resources:
    accountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort_key
            AttributeType: S 
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort_key
            KeyType: RANGE 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1        