Resources:
  PreSignupTriggerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName:
        Fn::Join:
          - ''
          -
            - 'arn:aws:lambda:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':'
            - 'function:${self:service.name}-${self:provider.stage}-pre-signup'
      SourceArn:
        Fn::GetAtt: [CognitoUserPool, Arn]